### ISSUE TITLE
Implement Catalog as an external contract

### ISSUE THREAD

**Issue by Maar-io** [rmrk-team/rmrk-ink#27]
Create separate Catalog (previously called Base) contract to implement many-to-many relation, as in evm implementation for [RMRKCatalog](https://github.com/rmrk-team/evm/blob/master/contracts/RMRK/catalog/RMRKCatalog.sol)

**Comment by steven2308** [comment]
On the standard, bases are associated through assets, and since a token may have many assets they already support multiple bases. 
To make sure we understand. Can you confirm if the problem is that at the moment, the base is part of the same contract?

**Comment by ilionic** [comment]
@Maar-io it looks like we need to create separate Base contract to implement many-to-many relation, as in evm implementation for [RMRKCatalog](https://github.com/rmrk-team/evm/blob/master/contracts/RMRK/catalog/RMRKCatalog.sol) ?

**Comment by Maar-io** [comment]
@boyswan @ilionic is this still the idea? Moving Base (catalog) to external contract.
This will give flexibility to reuse already deployed Catalogs and will reduce the contract storage size.
If we go with this I propose to work on it after 1.0.0 release

**Comment by steven2308** [comment]
Yes @Maar-io , this really important on the EVM implementation as it provides a lot of flexibility by a contract being able to use multiple catalogs, and gas savings since many contracts can reuse a catalog.

An even better way to look at it is that it is **assets** that are tied to catalogs, not contracts.  So a same token could have 3 assets, each pointing to a different catalog say each for a different metaverse.
